name: Deploy to EC2

on:
  push:
    branches:
      - master

jobs:
  deploy:
    name: Deploy to EC2
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v3

    - name: Set up SSH
      uses: webfactory/ssh-agent@v0.5.3
      with:
        ssh-private-key: ${{ secrets.SSH_PRIVATE_KEY }}

    - name: Update EC2 instance and reload application
      run: |
        ssh -o StrictHostKeyChecking=no ubuntu@${{ secrets.SERVER_HOST }} << 'EOF'
          set -e

          echo "Navigating to the project directory..."
          cd /var/www/PostInvest-Pro || { echo "Error: Project directory not found."; exit 1; }

          echo "Pulling latest changes from the repository..."
          git reset --hard || { echo "Error: Failed to reset repository."; exit 1; }
          git pull https://${{ secrets.PAT_TOKEN }}@github.com/hariharan2604/PostInvest-Pro.git || { echo "Error: Failed to pull latest changes."; exit 1; }

          echo "Installing dependencies..."
          npm install || { echo "Error: Failed to install dependencies."; exit 1; }

          echo "Updating env.."
          sudo cp .env.production .env

          echo "Running database migrations..."
          npx sequelize-cli db:migrate || { echo "Error: Database migration failed."; exit 1; }

          echo "Reloading PM2 process..."
          pm2 reload all || { echo "Error: Failed to reload PM2 process."; exit 1; }
          sudo service nginx restart
          echo "Deployment complete!"
        EOF
